version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4-management 
    container_name: rabbitmq
    ports:
      - "5672:5672"       # Porta para conexão da aplicação
      - "15672:15672"     # Porta do painel web
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbit-network

networks:
  rabbit-network:
    driver: bridge
