### Get all tickets
GET /api/v1/tickets HTTP/1.1
Host: localhost:8082
Accept: application/json


### Create a new ticket
POST /api/v1/tickets HTTP/1.1
Host: localhost:8082
Content-Type: application/json

{
    "action": "Formatar",
    "object": "Notebook",
    "details": "Formatar o notebook do cliente",
    "userId": 1
}

### Get a ticket by ID

GET /api/v1/tickets/buscar/1 HTTP/1.1
Host: localhost:8082
Content-Type: application/json


### Update a ticket by ID
PATCH http://localhost:8082/api/v1/tickets/mudar/1?status=RESOLVED
Content-Type: application/json
Host: localhost:8082

